Beloop\Component\User\Entity\User:
    type: entity
    repositoryClass: Beloop\Component\User\Repository\UserRepository
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        guest:
            column: guest
            type: boolean
        biography:
            column: biography
            type: text
            nullable: true
        website:
            column: website
            type: string
            length: 255
            nullable: true
        instagram:
            column: instagram
            type: string
            length: 255
            nullable: true
        avatarName:
            column: avatar
            type: string
            length: 255
            nullable: true

    manyToOne:
        language:
            targetEntity: Beloop\Component\Language\Entity\Interfaces\LanguageInterface
            joinColumn:
                name: language_iso
                referencedColumnName: iso
                nullable: true

    lifecycleCallbacks:
            preUpdate: [loadUpdateAt]
            prePersist: [loadUpdateAt]