services:

    #
    # Services
    #
    beloop.manager.password:
        class: Beloop\Component\User\Services\PasswordManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@beloop.event_dispatcher.password'
            - '@beloop.generator.sha1'

    #
    # Manager
    #
    beloop.manager.user:
        class: Beloop\Component\User\Services\UserManager
        arguments:
            - '@beloop.object_manager.user'
            - '@beloop.repository.user'

    #
    # CSV file transformer
    #
    beloop.csv_transformer.user:
        class: Beloop\Component\User\Transformer\ExtractUsersFromCSV
        arguments:
            - '@beloop.factory.user'
            - ['Email', 'First Name', 'Last Name']
        calls:
           - [setDelimiter, [';']]
